import { CommonModule } from '@angular/common';
import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormArray, FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { TablerIconsModule } from 'angular-tabler-icons';
import { ToastrService } from 'ngx-toastr';
import { Subject, debounceTime, distinctUntilChanged, switchMap } from 'rxjs';
import { CoreService } from 'src/app/services/core.service';
import { extractApiErrorMessage } from '../../utils/api-error.util';
import { OfferFormValue, PlatformOfferDetail } from './interfaces/platform-offer.model';
import { PlatformOffersService } from './services/platform-offers.service';

@Component({selector:'app-platform-offer-form',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterModule,TranslateModule,TablerIconsModule],templateUrl:'./platform-offer-form.component.html',styleUrl:'./platform-offers.component.scss'})
export class PlatformOfferFormComponent implements OnInit{
 private fb=inject(FormBuilder);private route=inject(ActivatedRoute);private router=inject(Router);private service=inject(PlatformOffersService);private core=inject(CoreService);private tr=inject(TranslateService);private toast=inject(ToastrService);private code$=new Subject<string>();
 dir=computed(()=>this.core.getOptionsSignal()().dir); id?:number; loading=signal(false);saving=signal(false);error=signal('');open=signal(new Set(['basics']));banner?:File;preview=signal('');codeState=signal<'idle'|'checking'|'ok'|'taken'>('idle');days=['Sat','Sun','Mon','Tue','Wed','Thu','Fri'];
 form=this.fb.group({internalNameAr:['',Validators.required],internalNameEn:['',Validators.required],externalNameAr:[''],externalNameEn:[''],descriptionAr:[''],descriptionEn:[''],triggerType:['Automatic',Validators.required],code:[''],discountType:['Percentage',Validators.required],discountValue:[null as number|null,[Validators.required,Validators.min(.01)]],maxDiscountAmount:[null as number|null],appliedTo:['AllUnits',Validators.required],unitIds:[[] as number[]],offerStartDate:[''],offerEndDate:[''],offerDaysOfWeek:[''],happyHourStart:[''],happyHourEnd:[''],stayStartDate:[''],stayEndDate:[''],stayDaysOfWeek:[''],maxTotalUsage:[null as number|null],maxDailyUsage:[null as number|null],maxDailyUsagePerUser:[null as number|null],maxTotalUsagePerUser:[null as number|null],minDaysBeforeArrival:[null as number|null],minStayDays:[null as number|null],maxStayDays:[null as number|null],allowedPaymentMethods:[''],minBookingAmount:[null as number|null],displayChannel:['All'],canBeCombined:[false],expirationPolicy:['WhicheverFirst'],loyaltyPointsMultiplier:[1],exclusionPeriods:this.fb.array([]),customMessages:this.fb.array([]),offerTerms:this.fb.array([])});
 get exclusions(){return this.form.controls.exclusionPeriods as FormArray}get messages(){return this.form.controls.customMessages as FormArray}get terms(){return this.form.controls.offerTerms as FormArray}
 ngOnInit(){const raw=this.route.snapshot.paramMap.get('id');if(raw)this.id=+raw;this.code$.pipe(debounceTime(450),distinctUntilChanged(),switchMap(code=>this.service.checkCode(code))).subscribe({next:r=>this.codeState.set(r.isAvailable?'ok':'taken'),error:()=>this.codeState.set('idle')});if(this.id)this.load();}
 toggle(k:string){this.open.update(s=>{const n=new Set(s);n.has(k)?n.delete(k):n.add(k);return n})}isOpen(k:string){return this.open().has(k)}
 load(){this.loading.set(true);this.service.get(this.id!).subscribe({next:d=>{this.patch(d);this.loading.set(false)},error:e=>{this.error.set(extractApiErrorMessage(e,this.tr.instant('d3.platformOffers.errors.detail')));this.loading.set(false)}})}
 patch(d:PlatformOfferDetail){const date=(v?:string|null)=>v?v.slice(0,16):'';this.form.patchValue({...d,offerStartDate:date(d.offerStartDate),offerEndDate:date(d.offerEndDate),stayStartDate:date(d.stayStartDate),stayEndDate:date(d.stayEndDate),unitIds:d.offerUnits.map(u=>u.unitId)} as any);this.preview.set(d.banner||'');d.exclusionPeriods.forEach(x=>this.exclusions.push(this.exclusion(x)));d.customMessages.forEach(x=>this.messages.push(this.message(x)));d.offerTerms.forEach(x=>this.terms.push(this.term(x)));}
 file(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(f){this.banner=f;this.preview.set(URL.createObjectURL(f));}}
 lang(){return this.router.url.split('/')[1]||'ar'}
 listLink(){return['/',this.lang(),'d3','platform-offers']}
 unitIdsText(){return (this.form.controls.unitIds.value||[]).join(', ')}
 setUnitIds(v:string){this.form.controls.unitIds.setValue(v.split(',').map(s=>+s.trim()).filter(n=>Number.isFinite(n)&&n>0))}
 codeChanged(v:string){if(this.form.value.triggerType==='Coupon'&&v.trim().length>2){this.codeState.set('checking');this.code$.next(v.trim())}else this.codeState.set('idle')}
 exclusion(v:any={}){return this.fb.group({id:[v.id],startDate:[v.startDate?.slice(0,16)||'',Validators.required],endDate:[v.endDate?.slice(0,16)||'',Validators.required],reason:[v.reason||'']})}message(v:any={}){return this.fb.group({id:[v.id],type:[v.type||'None',Validators.required],messageAr:[v.messageAr||'',Validators.required],messageEn:[v.messageEn||'',Validators.required]})}term(v:any={}){return this.fb.group({id:[v.id],termAr:[v.termAr||'',Validators.required],termEn:[v.termEn||'',Validators.required],order:[v.order??this.terms.length+1,Validators.required]})}
 submit(){const coupon=this.form.value.triggerType==='Coupon';this.form.controls.code.setValidators(coupon?[Validators.required]:[]);this.form.controls.code.updateValueAndValidity();if(this.form.invalid||this.codeState()==='taken'){this.form.markAllAsTouched();this.open.set(new Set(['basics','discount','scope','timing','stay','usage','settings','exclusions','messages','terms']));setTimeout(()=>document.querySelector<HTMLElement>('.ng-invalid:not(form)')?.focus());return;}this.saving.set(true);const value=this.form.getRawValue() as unknown as OfferFormValue;const onDone=(newId?:number)=>{this.saving.set(false);this.toast.success(this.tr.instant('d3.platformOffers.saved'));this.router.navigate(['/',this.lang(),'d3','platform-offers',this.id||newId]);};const onErr=(e:unknown)=>{this.saving.set(false);this.toast.error(extractApiErrorMessage(e,this.tr.instant('d3.platformOffers.errors.save')));};if(this.id)this.service.update(this.id,value,this.banner).subscribe({next:()=>onDone(),error:onErr});else this.service.create(value,this.banner).subscribe({next:r=>onDone(r),error:onErr})}
}
